### PR TITLE
Enable Service Worker (Fixes #143)

### LINKED ISSUE #143: Service Worker support
It'd allow the Web IDE website to work offline (this wouldn't affect the  actual Chrome Web App version)

### PR DESCRIPTION
**Pull request by jrstanley**
Here's an initial revision to the Service Worker logic (refs #143).

I have to confess that I've not used the Espruino Web IDE to its full extent (I have navigated around it for the purposes of testing), however I have a Puck.js arriving soon and I can rectify this then.

### What this PR does

1. Re-enables Service Worker (SW) registration.
1. Moves SW registration to the bottom of index.html, allowing initial resource downloads to be initiated before the SW attempts to fill its cache.
1. Removes some resources from the SW cache which didn't exist and would cause the SW registration to fail.
1. Removes some resources from the SW cache which seem irrelevant (EspruinoTools/LICENSE, EspruinoTools/package.json).
1. Restructures SW to add versioning and moves cached resources into its own array.
1. 'Namespaces' the cache name.
1. SW supports versioning by changing the VERSION variable, which will cause browsers to populate a brand new cache and discard the old cache when the new SW is active.
1. SW will fallback to the network if a requested resource is not in the cache (whereas before it would just fail).
1. Makes the SW cache insensitive to querystring parameters for all resources.

### Requires discussion or investigation
1. We don't remove the old v1 cache for anyone who might have it - is this important? We could add a specific check for this.
1. Is ignoring querystring parameters when returning resources from the cache safe? i.e. does the content of any resource change based on querystring parameters?
1. I'm aware of, but not familiar with, the fact that EspruinoWebIDE is provided in a number of formats (e.g. Chrome Web App, NPM (Electron?) and Web) - is there a risk of the SW interfering with these.
1. If any resources change, the SW must be updated with a new `VERSION` value for these to be updated in browsers using the SW. The approach of starting a new cache and removing the old one is straightforward from our perspective, however we could consider splitting out into multiple caches (eg. EspruinoTools, blockly, JS libs, data, and Web IDE/other) to allow more granular control of this. I'm not convinced it's worth it?
1. Are any resources not added to the cache which should be? I haven't identified any in my use of the app.
1. Are the any resources added to the cache which shouldn't be? I've not attempted to do any audit of this as yet, other than eyeballing the list of resources and seeing if they look sensible.

### CODE REVIEW

**Comment by gfwilliams** [comment]
Nice, thanks!

> We don't remove the old v1 cache for anyone who might have it - is this important?

I don't think so - virtually nobody should have it now as it was only ever enabled for a few days a long time ago.

> i.e. does the content of any resource change based on querystring parameters?

No, it's all static

> I'm aware of, but not familiar with, the fact that EspruinoWebIDE is provided in a number of formats (e.g. Chrome Web App, NPM (Electron?) and Web) - is there a risk of the SW interfering with these.

It's a good point. the Web app uses main.html, but some others do use `index.html` (for example the local Web IDE server, which can serve the IDE up from port 8080). What I tend to do for other stuff is check `window.location` and then only enable features (eg the SW) for espruino.com. We could do that?

> If any resources change, the SW must be updated with a new VERSION value for these to be updated in browsers using the SW. The approach of starting a new cache and removing the old one is straightforward from our perspective, however we could consider splitting out into multiple caches (eg. EspruinoTools, blockly, JS libs, data, and Web IDE/other) to allow more granular control of this. I'm not convinced it's worth it?

You're right - I think it's worth just ignoring it. Perhaps we could arrange that the list part of the file itself is created via a script, and the version is the git hash? It'd make things a lot less error-prone.

> Are any resources not added to the cache which should be? I haven't identified any in my use of the app.

I'd have thought it would complain if not. There is a special 'offline mode' that downloads all available modules/board description files for offline use - currently that's only enabled for the Chrome Web App, but if we uses a non-chrome-only storage mechanism then we could enable that.

I think it makes sense for that to be separate since library files tend to change a lot more often.

> Are the any resources added to the cache which shouldn't be?

It looks ok - I don't think there's anything obvious.

Do you think it's worth adding a specific check on the window's URL before I pull this, just to ensure there aren't any potential issues with other Web IDE uses?

Thanks!

**Comment by jrstanley** [comment]
No problem, and thank you for your responses.

> Perhaps we could arrange that the list part of the file itself is created via a script, and the version is the git hash? It'd make things a lot less error-prone.

Agreed. Shall we look at deploying this as-is for now, and then we could look at this as a follow-on option?

> There is a special 'offline mode' that downloads all available modules/board description files for offline use - currently that's only enabled for the Chrome Web App, but if we uses a non-chrome-only storage mechanism then we could enable that.

I'm wondering if this could be achieved by caching the offline.zip in the SW. It would require a variation of/SW detection in the offline.js and so would need to be careful that existing functionality isn't impacted. Something to look into separately, perhaps?

> Do you think it's worth adding a specific check on the window's URL before I pull this, just to ensure there aren't any potential issues with other Web IDE uses?

I'm not 100% sure it's necessary, but I think it makes sense to be cautious. I've updates this PR to add the check for www.espruino.com. I have seen a number of links go directly to GitHub Pages https://espruino.github.io/EspruinoWebIDE/ and I've included support for this also.

**Comment by gfwilliams** [comment]
Sorry for the delay - I was away last week. I will get to this soon though :)

**Comment by gfwilliams** [comment]
Looks good - so I just have to be sure to update `VERSION` and the files list whenever the IDE changes? I guess I could make a build script for that

**Comment by jrstanley** [comment]
Thanks @gfwilliams!

Yes that's right, just bump the `VERSION` and update the list of files.

If you happen to miss any files, the worst that should happen is it'll try to go to the network (and fail if offline) to get it.

However, if you keep files in the list which now 404 this will stop the updated SW from registering and the old one will remain.

**Comment by gfwilliams** [comment]
Great - do you know if it'll show any errors in the console if it does 404?

**Comment by jrstanley** [comment]
It should, although I've found this a little patchy in Chrome's DevTools. What you definitely should see is that the registration of the new Service Worker fails. Hopefully you see the failed fetch in the console/network tab, however I've had to inspect the Service Worker (separate DevTools instance) to see this in the past.

**Pull request merged**
