### PR TITLE
Blocky module for amperka's motor shield.

### PR DESCRIPTION
**Pull request by mickvav**
Hello. 
I've just got amperka's motor shield and decided to help my son deal with it using blocky GUI, but found that 
digitalWrite/analogWrite is not intuitive enought - so I've made some coding & testing after copy-pasteing Robot code - the result seems to work.
Idea - we have 2 blocks - direction and speed, available for each motor, managed by motorshield.

### CODE REVIEW

**Comment by gfwilliams** [comment]
Thanks - looks good (the motor shield stuff is still in there by default and there's no way to change the language without adding your own Blockly HTML though?).

**Comment by mickvav** [comment]
Well, I can comment out MotorShield stuff, if it matters. About localization - it's a point to discuss. Right now - yes, I mean that any not-straight-simple behavior should be explicitly enabled by user, demonstrating that he is skillful enough. I think, I can add config option like "Select language",  which adds corresponding code, but I am afraid that user would expect that all the GUI will be localized, not just blockly part. And I am not sure that I am ready to translate ALL the GUI :(.

**Comment by gfwilliams** [comment]
There's a forum thread asking about localisation too now :) http://forum.espruino.com/conversations/296674/#comment13344605

Sorry for the delay - I will get this merged, but I'm out of the country at the moment.

**Comment by gfwilliams** [comment]
Thanks!

**Comment by mickvav** [comment]
Great!

**Comment by gfwilliams** [comment]
I've updated the IDE online now - hopefully you can see what I've done? I made it so you can change language and add your motor shield stuff without having to install anything custom

**Pull request merged**
