### PR TITLE
Update tutorial.js

### PR DESCRIPTION
**Pull request by GrandVizierOlaf**
Allow for multiline detection of tags (as in tutorial 1 with mention of LEDs 2 and 3, [here](https://github.com/espruino/EspruinoWebIDE/blob/master/data/tutorials/1.js#L18)).

### CODE REVIEW

**Comment by GrandVizierOlaf** [comment]
To clarify why this change was needed, you can see when running through the first tutorial on a banglejs2 that it shows information about LED2 and LED3 (because of [this code](https://github.com/espruino/EspruinoWebIDE/blob/564bd9fb600bc224709b0450dbe350913f024c81/data/tutorials/1.js#L18)) when it is not supposed to, because the tag is on the previous line.

image

Really, that text should be updated to support LED2 and not LED3, but this is a broader feature enhancement and I believe addresses the intent of the tag as it exists in that section.

**Comment by gfwilliams** [comment]
Thanks! Does this definitely fix the issue? Because I'd imagine the issue here is that the board name is reported as BANGLEJS2 and we've only been checking against whether it was a PIXLJS?

**Comment by GrandVizierOlaf** [comment]
@gfwilliams you're right, I bought a banglejs2 and pixljs at the same time and think I got my wires crossed between finding, fixing, and documenting the issue.

To be (hopefully) 100% clear:

Without the change:

On a banglejs2:

> This returned =undefined because digitalWrite does not return a value, but the red light) should have lit up. You can turn the green and blue LEDs on using LED2 and LED3 respectively.
> 
> Now, turn the light off again by typing the same command with a 0 instead of a 1. Note that you can press the up arrow to go back to the previous line you entered, then can move the cursor with the left and right arrows. When you're done use the right arrow or End key to go to the end of the line before hitting enter.

On a pixljs:

> This returned =undefined because digitalWrite does not return a value, but the backlight) should have lit up. You can turn the green and blue LEDs on using LED2 and LED3 respectively.
> 
> Now, turn the light off again by typing the same command with a 0 instead of a 1. Note that you can press the up arrow to go back to the previous line you entered, then can move the cursor with the left and right arrows. When you're done use the right arrow or End key to go to the end of the line before hitting enter.

With the change:

On a banglejs2:

> This returned =undefined because digitalWrite does not return a value, but the red light) should have lit up.
> 
> You can turn the green and blue LEDs on using LED2 and LED3 respectively.
> 
> Now, turn the light off again by typing the same command with a 0 instead of a 1. Note that you can press the up arrow to go back to the previous line you entered, then can move the cursor with the left and right arrows. When you're done use the right arrow or End key to go to the end of the line before hitting enter.

On a pixljs:

> This returned =undefined because digitalWrite does not return a value, but the backlight) should have lit up.
> 
> Now, turn the light off again by typing the same command with a 0 instead of a 1. Note that you can press the up arrow to go back to the previous line you entered, then can move the cursor with the left and right arrows. When you're done use the right arrow or End key to go to the end of the line before hitting enter.

So, in summary, this adds support for multiline regex which corrects the incorrect information shown for a pixljs, but does not address the banglejs tags being needed. I can fix that in this MR or open a separate one, whichever you prefer @gfwilliams.

**Comment by gfwilliams** [comment]
Thanks! Merging now - and I'll add some tweaks for Bangle.js to the tutorial page

**Pull request merged**
