### PR TITLE
Resolves #218 - syntax highlghting added to JavaScript Editor

### LINKED ISSUE #218: Syntax highlighting - additional styles
The Web IDE is fantastic, so I am loathe to move back and forth between any other text editor. The only thing I'm missing is being able to work in my preferred syntax highlighting theme.

It looks like CodeMirror has a theme plugin for this - [CodeMirror (Source) Syntax Highlighting](https://ckeditor.com/cke4/addon/codemirror) ([demo](https://codemirror.net/demo/theme.html)) (if I understand correctly). Is it possible to integrate this into the Settings menu?

I'm afraid that I don't know/understand enough to give this a shot myself, but happy to test if it helps.

Cheers

### PR DESCRIPTION
**Pull request by huntlyc**
Pull request adds an option into the general settings to allow user to choose their preferred colour scheme from those provided for issue #218 

List of available themes: [https://codemirror.net/demo/theme.html](https://codemirror.net/demo/theme.html)

There's quite a few themes that can be used with the editor - maybe worth cherry picking popular ones?

### CODE REVIEW

**Comment by huntlyc** [comment]
@gfwilliams - totally agree!  They're quite small individually and could be combined into one sheet?   However, including just what's needed and no extra dead weight is the most sensible way forward.  Will give that a go.

**Comment by huntlyc** [comment]
Because editor changes don't kick in until after the page is reloaded, we could get away with dynamically loading the specific style sheet (if the user isn't using the default theme) just before the editor is created?

**Comment by gfwilliams** [comment]
This is looking great - thanks!

> Because editor changes don't kick in until after the page is reloaded

It looks like on here they're instant: https://codemirror.net/demo/theme.html

They do `editor.setOption("theme", theme);` - do you think you could give that a go? It would definitely be a nicer experience.

**Comment by huntlyc** [comment]
Thanks @gfwilliams - yeah, would be happy to have a look at that.  

While I'm there though, the keymap setting also doesn't kick in until after a reload - would you be happy for me to take a look at seeing if we can have that kick in immediately after a user updates their settings too?

**Comment by gfwilliams** [comment]
>  would you be happy for me to take a look at seeing if we can have that kick in immediately after a user updates their settings too?

More than happy - that'd be great!

**Comment by huntlyc** [comment]
Noticed the code hinting setting also required a reload so updated that too

**Comment by gfwilliams** [comment]
This looks great - thanks! I'll update espruino.com/ide sometime this week hopefully

**Pull request merged**
