### PR TITLE
Added border in bangle emulator

### PR DESCRIPTION
**Pull request by ff2005**
Just a very simple way to have borders on the bangle emulator.
There is a button to cycle through the colors ('FFF', 'FF0', 'F00', '000', '00F', '0FF').
image

### CODE REVIEW

**Comment by gfwilliams** [comment]
Thanks! And I guess this solves that MacOS issue where the rightmost column wouldn't show too

**Comment by ff2005** [comment]
Welcome.
I didn't remember to add the blue and pink from the Bangle.js 2, but if you have the precise colors, I can add then.

Has for the pixels, I think this will not fix it 😞 
g.fillRect(0,2,174,10);
image
g.fillRect(0,2,175,10);
image

**Comment by ff2005** [comment]
FYI .... the problem is with width and height
g.fillRect(0,0,176 - 2,176 - 2);
image

**Comment by ff2005** [comment]
But, this is strange 😕 
g.fillRect(0,10,176 - 2, 20);
g.fillRect(1,30,176 - 2, 40);
image

**Pull request merged**
